/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.presentation;

import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.business.SWAP;

/**
 *
 * @author rokai
 */
public class AlunoSolicitaTurno extends javax.swing.JFrame {

	private SWAP s;
	private DefaultTableModel t;
	/**
	 * Creates new form AlunoMain
	 */
	public AlunoSolicitaTurno() {
		initComponents();
		s = null;
	}
	
	/**
	 * Creates new form AlunoMain
	 * @param s
	 */
	public AlunoSolicitaTurno(SWAP s) {
		initComponents();
		this.s = s;
		this.jLabelInvalidoUC.setVisible(false);
		this.jLabelInvalidoTurno.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonSolicita = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUC = new javax.swing.JTextField();
        jTextFieldTurno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelInvalidoUC = new javax.swing.JLabel();
        jLabelInvalidoTurno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Solicita turno");

        jButtonSolicita.setText("Solicita");
        jButtonSolicita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSolicitaMouseClicked(evt);
            }
        });

        jLabel4.setText("UC");

        jTextFieldUC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUCFocusGained(evt);
            }
        });

        jTextFieldTurno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTurnoFocusGained(evt);
            }
        });

        jLabel5.setText("Turno");

        jLabelInvalidoUC.setForeground(new java.awt.Color(255, 0, 0));
        jLabelInvalidoUC.setText("Inválido!");

        jLabelInvalidoTurno.setForeground(new java.awt.Color(255, 0, 0));
        jLabelInvalidoTurno.setText("Inválido!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSolicita))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelInvalidoUC)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelInvalidoTurno)))
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldUC, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jTextFieldTurno)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabelInvalidoUC)
                    .addComponent(jLabelInvalidoTurno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSolicita)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	
    private void jButtonSolicitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSolicitaMouseClicked
        String uc = this.jTextFieldUC.getText();
		String turno = this.jTextFieldTurno.getText();
		if (uc != null && !uc.equals("")) {
			if (turno != null && !turno.equals("")) {
				try {
					if (s.solicitaTurno(uc, turno)) {
						this.dispose();
						JOptionPane.showMessageDialog(this.rootPane,
							"A sua troca foi realizada com sucesso.");
					}
					else {
						this.dispose();
						JOptionPane.showMessageDialog(this.rootPane,
							"Neste momento não existe nenhuma troca compativel.\n"
							+ "A sua solicitação foi adicionada à fila de espera.");
						new AlunoSolicitacoesTurno(s).setVisible(true);
					}
				} catch (SQLException ex) {
					Logger.getLogger(AlunoSolicitaTurno.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
			else
				this.jLabelInvalidoTurno.setVisible(true);
		}
		else
			this.jLabelInvalidoUC.setVisible(true);
			
    }//GEN-LAST:event_jButtonSolicitaMouseClicked

    private void jTextFieldUCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUCFocusGained
        this.jLabelInvalidoUC.setVisible(false);
    }//GEN-LAST:event_jTextFieldUCFocusGained

    private void jTextFieldTurnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTurnoFocusGained
        this.jLabelInvalidoTurno.setVisible(false);
    }//GEN-LAST:event_jTextFieldTurnoFocusGained

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AlunoSolicitaTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AlunoSolicitaTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AlunoSolicitaTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AlunoSolicitaTurno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AlunoSolicitaTurno().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSolicita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelInvalidoTurno;
    private javax.swing.JLabel jLabelInvalidoUC;
    private javax.swing.JTextField jTextFieldTurno;
    private javax.swing.JTextField jTextFieldUC;
    // End of variables declaration//GEN-END:variables
}
