/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.presentation;

import java.util.ArrayList;
import main.business.SWAP;
import main.business.SolicitacaoTroca;

/**
 *
 * @author rokai
 */
public class AnalisarTrocas extends javax.swing.JFrame {

	private SWAP s;
	private String codUC;
	private ArrayList<String[]> solicitacoes;
	//Diz qual a solicitacao que está pronta a ser analisada
	private int solicitacaoON;
	
	/**
	 * Creates new form AnalisarTrocas
	 */
	public AnalisarTrocas() {
		initComponents();
	}
	
	/**
	 * Creates new form AnalisarTrocas
	 */
	public AnalisarTrocas(SWAP s, String codUC) {
		initComponents();
		this.jLabelInvalidoPesqCodAluno.setVisible(false);
		this.jLabelSolicitacoesVazia.setVisible(false);
		this.s = s;
		this.codUC = codUC;
		
		this.solicitacoes = s.getSolicitacoesUC(codUC);
		this.trataSeExisteSolicitacaoTroca();
		
		this.jTextFieldCodAluno.setEditable(false);
		this.jTextFieldTurnoS.setEditable(false);
		this.jTextFieldTurnoD.setEditable(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldPesqCodAluno = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodAluno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTurnoS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTurnoD = new javax.swing.JTextField();
        jLabelSolicitacoesVazia = new javax.swing.JLabel();
        jButtonRejeitar = new javax.swing.JButton();
        jButtonAceitar = new javax.swing.JButton();
        jButtonAvancar = new javax.swing.JButton();
        jLabelInvalidoPesqCodAluno = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Analisar trocas");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Insira o número do aluno da troca em questão.");

        jTextFieldPesqCodAluno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldPesqCodAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPesqCodAlunoFocusGained(evt);
            }
        });

        jButtonPesquisar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPesquisarMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Número do aluno");

        jTextFieldCodAluno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Turno de origem");

        jTextFieldTurnoS.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Turno de destino");

        jTextFieldTurnoD.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabelSolicitacoesVazia.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelSolicitacoesVazia.setForeground(new java.awt.Color(255, 0, 0));
        jLabelSolicitacoesVazia.setText("Não existe mais solicitações");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldTurnoS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldCodAluno, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldTurnoD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSolicitacoesVazia)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSolicitacoesVazia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTurnoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTurnoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonRejeitar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonRejeitar.setText("Rejeitar");
        jButtonRejeitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRejeitarMouseClicked(evt);
            }
        });

        jButtonAceitar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAceitar.setText("Aceitar");
        jButtonAceitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAceitarMouseClicked(evt);
            }
        });

        jButtonAvancar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonAvancar.setText("Avançar");
        jButtonAvancar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAvancarMouseClicked(evt);
            }
        });

        jLabelInvalidoPesqCodAluno.setForeground(new java.awt.Color(255, 0, 0));
        jLabelInvalidoPesqCodAluno.setText("Inválido!");

        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenu1.setText("Ficheiro");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPesqCodAluno)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonAceitar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRejeitar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAvancar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelInvalidoPesqCodAluno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPesqCodAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jLabelInvalidoPesqCodAluno))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRejeitar)
                    .addComponent(jButtonAceitar)
                    .addComponent(jButtonAvancar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void trataSeExisteSolicitacaoTroca () {
		if (solicitacoes.size() > 0) {
			solicitacaoON = 0;
			this.jButtonAceitar.setEnabled(true);
			this.jButtonRejeitar.setEnabled(true);
			this.jButtonAvancar.setEnabled(true);
			this.jButtonPesquisar.setEnabled(true);
			this.printSolicitacaoTroca();
		}
		else {
			solicitacaoON = -1;
			this.jLabelSolicitacoesVazia.setVisible(true);
			this.jButtonAceitar.setVisible(false);
			this.jButtonRejeitar.setVisible(false);
			this.jButtonAvancar.setVisible(false);
			this.jButtonPesquisar.setVisible(false);
		}
	}
	
	private void printSolicitacaoTroca () {
		String[] st = solicitacoes.get(solicitacaoON);
		String codAluno = st[0];
		String codTurnoS = st[1];
		String codTurnoD = st[2];
		this.jTextFieldCodAluno.setText(codAluno);
		this.jTextFieldTurnoS.setText(codTurnoS);
		this.jTextFieldTurnoD.setText(codTurnoD);
	}
	
    private void jButtonPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPesquisarMouseClicked
        String pesqCodAluno = this.jTextFieldPesqCodAluno.getText();
		if (pesqCodAluno != null && !pesqCodAluno.equals("")) {
			for (int i = 0; i < solicitacoes.size(); i++) {
				String[] st = solicitacoes.get(i);
				String codAluno = st[0];
				if (codAluno.equals(pesqCodAluno))
					solicitacaoON = i;
					this.printSolicitacaoTroca();
			}
		}
		else
			this.jLabelInvalidoPesqCodAluno.setVisible(true);
			
    }//GEN-LAST:event_jButtonPesquisarMouseClicked

    private void jTextFieldPesqCodAlunoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPesqCodAlunoFocusGained
        this.jLabelInvalidoPesqCodAluno.setVisible(false);
    }//GEN-LAST:event_jTextFieldPesqCodAlunoFocusGained

    private void jButtonAceitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAceitarMouseClicked
   		String codAluno = this.jTextFieldCodAluno.getText();
		String codTurnoS = this.jTextFieldTurnoS.getText();
		String codTurnoD = this.jTextFieldTurnoD.getText();
		s.analisaTroca(codAluno,codUC,codTurnoS,codTurnoD,true);
		solicitacoes.remove(solicitacaoON);
		this.trataSeExisteSolicitacaoTroca();
    }//GEN-LAST:event_jButtonAceitarMouseClicked

    private void jButtonRejeitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRejeitarMouseClicked
        String codAluno = this.jTextFieldCodAluno.getText();
		String codTurnoD = this.jTextFieldTurnoD.getText();
        String codTurnoS = this.jTextFieldTurnoS.getText();
        s.analisaTroca(codAluno,codUC,codTurnoS,codTurnoD,false);
		solicitacoes.remove(solicitacaoON);
		this.trataSeExisteSolicitacaoTroca();
    }//GEN-LAST:event_jButtonRejeitarMouseClicked

    private void jButtonAvancarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAvancarMouseClicked
        if (solicitacaoON < solicitacoes.size()-1) {
			this.solicitacaoON++;
		}
		this.printSolicitacaoTroca();
    }//GEN-LAST:event_jButtonAvancarMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AnalisarTrocas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AnalisarTrocas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AnalisarTrocas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AnalisarTrocas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AnalisarTrocas().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceitar;
    private javax.swing.JButton jButtonAvancar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonRejeitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelInvalidoPesqCodAluno;
    private javax.swing.JLabel jLabelSolicitacoesVazia;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldCodAluno;
    private javax.swing.JTextField jTextFieldPesqCodAluno;
    private javax.swing.JTextField jTextFieldTurnoD;
    private javax.swing.JTextField jTextFieldTurnoS;
    // End of variables declaration//GEN-END:variables
}
