/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.ArrayList;
import main.business.SWAP;

/**
 *
 * @author rokai
 */
public class Inscricao extends javax.swing.JFrame {

	private SWAP s;
	private ArrayList<String> ucsEscolhidas;
	
	/**
	 * Creates new form Inscricao
	 */
	public Inscricao() {
		initComponents();
	}
	
	/**
	 * Creates new form Inscricao
	 * @param s
	 */
	public Inscricao(SWAP s) {
		initComponents();
		this.s = s;
		this.ucsEscolhidas = new ArrayList<>();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxAnalise = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBoxEES = new javax.swing.JCheckBox();
        jCheckBoxAlgebra = new javax.swing.JCheckBox();
        jCheckBoxPF = new javax.swing.JCheckBox();
        jCheckBoxCalculo = new javax.swing.JCheckBox();
        jCheckBoxTMD = new javax.swing.JCheckBox();
        jCheckBoxSC = new javax.swing.JCheckBox();
        jCheckBoxLI1 = new javax.swing.JCheckBox();
        jCheckBoxTFM = new javax.swing.JCheckBox();
        jCheckBoxLogica = new javax.swing.JCheckBox();
        jCheckBoxPI = new javax.swing.JCheckBox();
        jCheckBoxLI2 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jCheckBoxEletro = new javax.swing.JCheckBox();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jCheckBoxCD = new javax.swing.JCheckBox();
        jCheckBoxArqComp = new javax.swing.JCheckBox();
        jCheckBoxEE = new javax.swing.JCheckBox();
        jCheckBoxALG = new javax.swing.JCheckBox();
        jCheckBoxEA = new javax.swing.JCheckBox();
        jCheckBoxCP = new javax.swing.JCheckBox();
        jCheckBoxISD = new javax.swing.JCheckBox();
        jCheckBoxLI3 = new javax.swing.JCheckBox();
        jCheckBoxPOO = new javax.swing.JCheckBox();
        jCheckBoxSO = new javax.swing.JCheckBox();
        jCheckBoxOpcao = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jCheckBoxCC = new javax.swing.JCheckBox();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jCheckBoxMNONL = new javax.swing.JCheckBox();
        jCheckBoxDSS = new javax.swing.JCheckBox();
        jCheckBoxMDIO = new javax.swing.JCheckBox();
        jCheckBoxBD = new javax.swing.JCheckBox();
        jCheckBoxRC = new javax.swing.JCheckBox();
        jCheckBoxCG = new javax.swing.JCheckBox();
        jCheckBoxSD = new javax.swing.JCheckBox();
        jCheckBoxLI4 = new javax.swing.JCheckBox();
        jCheckBoxMEIO = new javax.swing.JCheckBox();
        jCheckBoxPL = new javax.swing.JCheckBox();
        jCheckBoxSRCR = new javax.swing.JCheckBox();
        jButtonInscrever = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inscrição");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Selecione as UC's que pretende frequentar este semestre.");

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("1º semestre");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Tópicos de Física Moderna");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Lógica EI");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Programação Imperativa");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setText("Laboratórios de Informática II");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("2º semestre");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Cálculo");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Álgebra linear");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Elementos de Engenharia de Sistemas");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Programação Funcional");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Tópicos de Matemática Discreta");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Laboratórios de Informática 1");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Sistemas de Computação");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Análise");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(jCheckBoxCalculo))
                                            .addComponent(jCheckBoxAlgebra, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jCheckBoxEES, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jCheckBoxPF, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jCheckBoxTMD, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jCheckBoxLI1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel15))))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(jCheckBoxSC))
                                            .addComponent(jCheckBoxAnalise, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jCheckBoxTFM, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jCheckBoxLogica, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jCheckBoxPI, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jCheckBoxLI2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jCheckBoxCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxAlgebra, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxEES, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxPF, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxTMD, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxLI1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jCheckBoxSC, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBoxAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel12))
                                    .addComponent(jCheckBoxTFM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addComponent(jLabel13))
                            .addComponent(jCheckBoxLogica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel14))
                    .addComponent(jCheckBoxPI, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jCheckBoxLI2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("1º ano", jPanel1);

        jPanel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel73.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel73.setText("1º semestre");

        jLabel74.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel74.setText("Laboratórios de Informática III");

        jLabel75.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel75.setText("Programação Orientada aos Objetos");

        jLabel76.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel76.setText("Sistemas Operativos");

        jLabel77.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel77.setText("Opção UMinho");

        jLabel78.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel78.setText("2º semestre");

        jLabel79.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel79.setText("Algoritmos e Complexidade");

        jLabel80.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel80.setText("Arquitetura de Computadores");

        jLabel81.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel81.setText("Comunicação de Dados");

        jLabel82.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel82.setText("Engenharia Económica");

        jLabel83.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel83.setText("Estatística Aplicada");

        jLabel84.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel84.setText("Introdução aos Sistemas Dinâmicos");

        jLabel85.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel85.setText("Cálculo de Programas");

        jLabel86.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel86.setText("Eletromagnetismo EE");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel80, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel81, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel82, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel83, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel84, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel79, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(jCheckBoxALG))
                                            .addComponent(jCheckBoxArqComp, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jCheckBoxCD, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jCheckBoxEE, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jCheckBoxEA, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jCheckBoxISD, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel73)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel78, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel86)
                                    .addComponent(jLabel74)
                                    .addComponent(jLabel75)
                                    .addComponent(jLabel76)
                                    .addComponent(jLabel85)
                                    .addComponent(jLabel77))))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(jCheckBoxCP))
                                            .addComponent(jCheckBoxEletro, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jCheckBoxLI3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jCheckBoxPOO, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jCheckBoxSO, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jCheckBoxOpcao, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel73)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel79)
                    .addComponent(jCheckBoxALG, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxArqComp, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel80))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxCD, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel81))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxEE, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel82))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxEA, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel83))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxISD, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel84))
                .addGap(18, 18, 18)
                .addComponent(jLabel78)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel85)
                                            .addComponent(jCheckBoxCP, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBoxEletro, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel86))
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel74))
                                    .addComponent(jCheckBoxLI3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addComponent(jLabel75))
                            .addComponent(jCheckBoxPOO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel76))
                    .addComponent(jCheckBoxSO, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel77)
                    .addComponent(jCheckBoxOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("2º ano", jPanel6);

        jPanel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel87.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel87.setText("1º semestre");

        jLabel88.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel88.setText("Laboratórios de Informática IV");

        jLabel89.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel89.setText("Modelos Estocásticos de Investigação Operacional");

        jLabel90.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel90.setText("Processamento de Linguagens");

        jLabel91.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel91.setText("Sistemas de Representação de Conhecimento e Raciocínio");

        jLabel92.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel92.setText("2º semestre");

        jLabel93.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel93.setText("Bases de Dados");

        jLabel94.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel94.setText("Desenvolvimento de Sistemas de Software");

        jLabel95.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel95.setText("Métodos Numéricos e Otimização Não Linear");

        jLabel96.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel96.setText("\tModelos Determinísticos de Investigação Operacional");

        jLabel97.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel97.setText("Redes de Computadores");

        jLabel98.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel98.setText("\tSistemas Distribuídos");

        jLabel99.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel99.setText("Computação Gráfica");

        jLabel100.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel100.setText("Comunicações por Computador");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel94, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel95, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel96, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel97, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel98, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel93, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(jCheckBoxBD))
                                            .addComponent(jCheckBoxDSS, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jCheckBoxMNONL, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jCheckBoxMDIO, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jCheckBoxRC, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jCheckBoxSD, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel87)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel92, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel100)
                                    .addComponent(jLabel88)
                                    .addComponent(jLabel89)
                                    .addComponent(jLabel90)
                                    .addComponent(jLabel99)
                                    .addComponent(jLabel91))))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(jCheckBoxCG))
                                            .addComponent(jCheckBoxCC, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jCheckBoxLI4, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jCheckBoxMEIO, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jCheckBoxPL, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jCheckBoxSRCR, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel87)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel93)
                    .addComponent(jCheckBoxBD, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxDSS, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel94))
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxMNONL, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel95))
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxMDIO, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel96))
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxRC, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel97))
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxSD, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel98))
                .addGap(18, 18, 18)
                .addComponent(jLabel92)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel99)
                                            .addComponent(jCheckBoxCG, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBoxCC, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel100))
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel88))
                                    .addComponent(jCheckBoxLI4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addComponent(jLabel89))
                            .addComponent(jCheckBoxMEIO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel90))
                    .addComponent(jCheckBoxPL, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel91)
                    .addComponent(jCheckBoxSRCR, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("3º ano", jPanel7);

        jButtonInscrever.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonInscrever.setText("Inscrever");
        jButtonInscrever.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonInscreverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonInscrever))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonInscrever)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInscreverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInscreverMouseClicked
        if (this.jCheckBoxArqComp.isSelected())
			ucsEscolhidas.add("AC");                                              
        if (this.jCheckBoxAlgebra.isSelected())
			ucsEscolhidas.add("AL");                                              
        if (this.jCheckBoxALG.isSelected())
			ucsEscolhidas.add("ALG");                                              
        if (this.jCheckBoxAnalise.isSelected())
			ucsEscolhidas.add("ANALISE");                                              
        if (this.jCheckBoxBD.isSelected())
			ucsEscolhidas.add("BD");                                              
        if (this.jCheckBoxCalculo.isSelected())
			ucsEscolhidas.add("Calc");                                              
        if (this.jCheckBoxCC.isSelected())
			ucsEscolhidas.add("CC");                                              
        if (this.jCheckBoxCD.isSelected())
			ucsEscolhidas.add("CD");                                              
        if (this.jCheckBoxCG.isSelected())
			ucsEscolhidas.add("CG");                                              
        if (this.jCheckBoxCP.isSelected())
			ucsEscolhidas.add("CP");                                              
        if (this.jCheckBoxDSS.isSelected())
			ucsEscolhidas.add("DSS");                                              
        if (this.jCheckBoxEA.isSelected())
			ucsEscolhidas.add("EA");                                              
        if (this.jCheckBoxEE.isSelected())
			ucsEscolhidas.add("EE");                                              
        if (this.jCheckBoxEES.isSelected())
			ucsEscolhidas.add("EES");                                              
        if (this.jCheckBoxEletro.isSelected())
			ucsEscolhidas.add("EM");                                              
        if (this.jCheckBoxISD.isSelected())
			ucsEscolhidas.add("ISD");                                              
        if (this.jCheckBoxLI1.isSelected())
			ucsEscolhidas.add("LI1");                                              
        if (this.jCheckBoxLI2.isSelected())
			ucsEscolhidas.add("LI2");                                              
        if (this.jCheckBoxLI3.isSelected())
			ucsEscolhidas.add("LI3");                                              
        if (this.jCheckBoxLI4.isSelected())
			ucsEscolhidas.add("LI4");                                              
        if (this.jCheckBoxLogica.isSelected())
			ucsEscolhidas.add("LOG");                                              
        if (this.jCheckBoxMDIO.isSelected())
			ucsEscolhidas.add("MDIO");                                              
        if (this.jCheckBoxMEIO.isSelected())
			ucsEscolhidas.add("MEIO");                                              
        if (this.jCheckBoxMNONL.isSelected())
			ucsEscolhidas.add("MNOnL");                                              
        if (this.jCheckBoxPF.isSelected())
			ucsEscolhidas.add("PF");                                              
        if (this.jCheckBoxPI.isSelected())
			ucsEscolhidas.add("PI");                                              
        if (this.jCheckBoxPL.isSelected())
			ucsEscolhidas.add("PL");                                              
        if (this.jCheckBoxPOO.isSelected())
			ucsEscolhidas.add("POO");                                              
        if (this.jCheckBoxRC.isSelected())
			ucsEscolhidas.add("RC");                                              
        if (this.jCheckBoxSC.isSelected())
			ucsEscolhidas.add("SC");                                              
        if (this.jCheckBoxSD.isSelected())
			ucsEscolhidas.add("SD");                                              
        if (this.jCheckBoxSO.isSelected())
			ucsEscolhidas.add("SO");                                              
        if (this.jCheckBoxSRCR.isSelected())
			ucsEscolhidas.add("SRCR");                                              
        if (this.jCheckBoxTFM.isSelected())
			ucsEscolhidas.add("TFM");                                              
        if (this.jCheckBoxTMD.isSelected())
			ucsEscolhidas.add("TMD");
		
		s.inscreveNasUCs(ucsEscolhidas);
		this.dispose();
    }//GEN-LAST:event_jButtonInscreverMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Inscricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Inscricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Inscricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Inscricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Inscricao().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInscrever;
    private javax.swing.JCheckBox jCheckBoxALG;
    private javax.swing.JCheckBox jCheckBoxAlgebra;
    private javax.swing.JCheckBox jCheckBoxAnalise;
    private javax.swing.JCheckBox jCheckBoxArqComp;
    private javax.swing.JCheckBox jCheckBoxBD;
    private javax.swing.JCheckBox jCheckBoxCC;
    private javax.swing.JCheckBox jCheckBoxCD;
    private javax.swing.JCheckBox jCheckBoxCG;
    private javax.swing.JCheckBox jCheckBoxCP;
    private javax.swing.JCheckBox jCheckBoxCalculo;
    private javax.swing.JCheckBox jCheckBoxDSS;
    private javax.swing.JCheckBox jCheckBoxEA;
    private javax.swing.JCheckBox jCheckBoxEE;
    private javax.swing.JCheckBox jCheckBoxEES;
    private javax.swing.JCheckBox jCheckBoxEletro;
    private javax.swing.JCheckBox jCheckBoxISD;
    private javax.swing.JCheckBox jCheckBoxLI1;
    private javax.swing.JCheckBox jCheckBoxLI2;
    private javax.swing.JCheckBox jCheckBoxLI3;
    private javax.swing.JCheckBox jCheckBoxLI4;
    private javax.swing.JCheckBox jCheckBoxLogica;
    private javax.swing.JCheckBox jCheckBoxMDIO;
    private javax.swing.JCheckBox jCheckBoxMEIO;
    private javax.swing.JCheckBox jCheckBoxMNONL;
    private javax.swing.JCheckBox jCheckBoxOpcao;
    private javax.swing.JCheckBox jCheckBoxPF;
    private javax.swing.JCheckBox jCheckBoxPI;
    private javax.swing.JCheckBox jCheckBoxPL;
    private javax.swing.JCheckBox jCheckBoxPOO;
    private javax.swing.JCheckBox jCheckBoxRC;
    private javax.swing.JCheckBox jCheckBoxSC;
    private javax.swing.JCheckBox jCheckBoxSD;
    private javax.swing.JCheckBox jCheckBoxSO;
    private javax.swing.JCheckBox jCheckBoxSRCR;
    private javax.swing.JCheckBox jCheckBoxTFM;
    private javax.swing.JCheckBox jCheckBoxTMD;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
